// Asslam o Alaikum
console.log(   )
console.log(" Hi This is Ali Ayaz")
console.log(   )
console.log(" This is Hello World or You may call it its A.I world")
console.log(   )
console.log(" In this fastest growing world you have to pick up yourself fast as per world")
console.log(   )
console.log(" Other wise theres no future for You . so i am here in kind Circle of")
console.log(   )
console.log(" Dearest Sir, Kamran Khan Tessori sb,  and best persnality Sir Zia Khan & its team")
console.log(   )
console.log("Its my first Class of Typescript & I am enjoying it")